version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - ./backend:/app
      - media_volume:/app/midia

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

volumes:
  media_volume: